#!/bin/sh -e
# This shell script must be run as root

run_in_chroot()
{
    echo "Running in chroot: $1"
    # Note: we execute the command in a login shell rather than execute it
    # directly because this makes the $PATH get set up correctly.
    DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true \
	LC_ALL=C LANGUAGE=C LANG=C chroot "$ROOTDIR" /bin/sh -l -c "$1"
}

OUTPUT=$1
PACKAGES_LIST=$2
OVERLAY_DIR=$3

MIRROR=http://mirrors.kernel.org/debian
ROOTDIR=rootfs
PACKAGES="perl bc ifupdown isc-dhcp-client resolvconf systemd systemd-sysv udev wget"
if test -f $PACKAGES_LIST ; then
    PACKAGES="$PACKAGES $(cat $PACKAGES_LIST)"
fi
PACKAGES=$(echo $PACKAGES | sed 's/ /,/g')

apt-get install -y debootstrap
mkdir -p $ROOTDIR
debootstrap --variant=minbase --include=$PACKAGES bookworm $ROOTDIR $MIRROR
tar -C $OVERLAY_DIR \
	--owner=root --group=root --mode=go+u-w -c . | tar -C $ROOTDIR -x
run_in_chroot "systemctl disable systemd-timesyncd"
run_in_chroot "systemctl enable ktest.service"
run_in_chroot "apt clean"

# clean up useless files
find $ROOTDIR/usr/share/doc -type f | grep -v copyright | xargs rm
find $ROOTDIR/usr/share/doc -mindepth 2 -type l | xargs rm
find $ROOTDIR/usr/share/doc -type d | xargs rmdir --ignore-fail-on-non-empty -p
rm -rf $ROOTDIR/usr/share/man
find $ROOTDIR/var/log -type f | xargs rm

shift 3
bin/mkfs.erofs $@ $OUTPUT $ROOTDIR
bin/fsck.erofs $OUTPUT
